package lk.ijse.spring;

import lk.ijse.spring.config.AppConfig;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class AppInitializer {
    public static void main(String[] args) {
        AnnotationConfigApplicationContext ctx=new AnnotationConfigApplicationContext();
        ctx.register(AppConfig.class);
        ctx.refresh();
        ctx.registerShutdownHook();
    }
}
/*
Bean Two  ApplicationContextAware.....
Bean Two  InitializingBean.....
lk.ijse.spring.bean.Bean_Two@279ad2e3
lk.ijse.spring.bean.Bean_Two@279ad2e3
Spring Bean One Instantiated......
Bean_One  BeanFactoryAware.....
Bean_One   BeanNameAware.....
Bean_One  ApplicationContextAware.....
Bean_One  InitializingBean.....
Bean_One  DisposableBean.....
Bean Two  DisposableBean.....
*/