package lk.ijse.spring;

import lk.ijse.spring.config.AppConfig;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class AppInitializer {
    public static void main(String[] args) {
        AnnotationConfigApplicationContext ctx=new AnnotationConfigApplicationContext();
        ctx.register(AppConfig.class);
        ctx.refresh();
        ctx.registerShutdownHook();
    }
}
/*
Bean One Bean Instantiated....
Bean One NameAware....
Bean One Bean FactoryAware....
Bean One Application ContextAware....
Bean One Initializing Bean....
Bean One Disposable Bean....
*/

/*----------------DB Connection is Not My Class But we Can add this Class @Bean Annotation -------------------*/

/*

Bean One Bean Instantiated....
Bean One NameAware....
Bean One Bean FactoryAware....
Bean One Application ContextAware....
Bean One Initializing Bean....
DBConnection  Instantiated....
DBConnection  NameAware....
DBConnection  Bean FactoryAware....
DBConnection  Application ContextAware....
DBConnection  Initializing Bean....
DBConnection  Disposable Bean....
Bean One Disposable Bean....

*/